use_frameworks!

platform :ios, '10.0'

target 'REIShopKit_Example' do
  pod 'ACPAnalytics', '~> 2.0'
  #pod 'RxSwift'
  pod 'REIShopKit', :path => '../'

  target 'REIShopKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
